spring:
  application:
    name: t1-java-demo
  datasource:
    url: "jdbc:postgresql://localhost:5432/t1_java_db"
    username: "postgres"
    password: "postgres"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

server:
  port: 8090

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: ${KAFKA_SERVER:localhost:9092}
    consumer:
      group-id: t1-demo
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered
      client_transactions: t1_demo_client_transactions

    listener:
      poll-timeout: 1000


track:
  errors-to-track: JsonParseException, IOException
  method-execution-time-limit-ms: 500

  kafka:
    enabled: ${TRACK_KAFKA_LOG_ENABLED:true}
    bootstrap-server: localhost:9092
    data-source-error-topic: t1_demo_data_source_error
    data-source-error-header: DATA_SOURCE
    metrics-topic: t1_demo_metrics
    metrics-header: METRICS
    time-limit-exceed: t1_demo_time_limit_exceed
  db:
    enabled: false
  time-limit-exceed: 1000
  log-level: DEBUG
